# Generated by Django 6.0.3 on 2026-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
